version: '3'
services: 
  server:
    environment:
      - SERVER_ADDR=http://server:8888
    build: ./server
  client:
    build: ./client
    restart: always
    environment:
      - SERVER_ADDR=http://server:8888
